### ISSUE TITLE
Opens and Closes Immediately 

### ISSUE THREAD

**Issue by BiggieCheese1337** [juryben/XboxKeyboardMouse#120]
When I open the app. It runs and then closes.

**Comment by WummoFTW** [comment]
Same to me

**Comment by Herbie74** [comment]
For the past 3 weeks I had the same problem...

Turns uut the ones that can read have an advantage ;)

I'm on a x64 system so I just installed the x64 version SlimDX..  and had the described crashes...

To fix also install the x86 version, instantly worked for me!

**Comment by airsquared** [comment]
Try the troubleshooting instructions at #116.
