### ISSUE TITLE
Recommend a ClickOnce installer for the non-technical users

### ISSUE THREAD

**Issue by DavidRieman** [juryben/XboxKeyboardMouse#90]
ClickOnce installers are actually pretty neat, simple, and handy.  They basically provide auto-update scenarios to the users for very little effort, on top of providing simple install for the user.  A user would launch the app, and it would check the URL of your choosing (e.g. some GitHub file endpoint) and it would detect a new version and offer to upgrade.  There's a few articles I see for this like: https://refactorsaurusrex.com/post/2015/how-to-host-a-clickonce-installer-on-github/

**Comment by DavidRieman** [comment]
IIRC ClickOnce installer prep is pretty good at auto-detecting what binaries go in the package, but can be given additional hints.  I think the biggest deal is we'd probably have to adjust where the presets get saved/loaded from, to a proper user folder or something (which is best practice anyway but pretty much enforced by the ClickOnce install location being locked down against file writes).

**Comment by CallumCarmicheal** [comment]
Ill look into this after i've gone through my current todo list.
